apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  labels:
    gls-demos: "true"
  name: openshift-metering
  namespace: openshift-metering
spec:
  targetNamespaces:
  - openshift-metering
